Repository brain-tec/pos, pull requests merged in 2023-10, with the labels that each got.

#422 Syncing from upstream OCA/pos (14.0)
  README.md
  pos_pricelist_show_discount/README.rst
  pos_pricelist_show_discount/__init__.py
  pos_pricelist_show_discount/__manifest__.py
  pos_pricelist_show_discount/demo/pos_config_demo.xml
  pos_pricelist_show_discount/demo/product_pricelist_demo.xml
  pos_pricelist_show_discount/demo/res_users_demo.xml
  pos_pricelist_show_discount/i18n/it.po
  pos_pricelist_show_discount/i18n/pos_pricelist_show_discount.pot
  pos_pricelist_show_discount/models/__init__.py
  pos_pricelist_show_discount/models/pos_config.py
  pos_pricelist_show_discount/readme/CONFIGURE.rst
  pos_pricelist_show_discount/readme/CONTRIBUTORS.rst
  pos_pricelist_show_discount/readme/DESCRIPTION.rst
  pos_pricelist_show_discount/readme/USAGE.rst
  pos_pricelist_show_discount/static/description/icon.png
  pos_pricelist_show_discount/static/description/index.html
  pos_pricelist_show_discount/static/src/js/models.js
  pos_pricelist_show_discount/static/src/xml/Orderline.xml
  pos_pricelist_show_discount/static/tests/tours/helpers/ProductScreenCustomTourMethods.js
  pos_pricelist_show_discount/static/tests/tours/pos_discount_ref_pricelist_tour.js
  pos_pricelist_show_discount/templates/assets.xml
  pos_pricelist_show_discount/tests/__init__.py
  pos_pricelist_show_discount/tests/test_pos_config_discount_pricelist.py
  pos_pricelist_show_discount/tests/test_pos_pricelist_show_discount.py
  pos_pricelist_show_discount/views/pos_config_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/pos_pricelist_show_discount/odoo/addons/pos_pricelist_show_discount
  setup/pos_pricelist_show_discount/setup.py
Labels: 14.0

#423 Syncing from upstream OCA/pos (16.0)
  README.md
  pos_sale_order_print/README.rst
  pos_sale_order_print/__init__.py
  pos_sale_order_print/__manifest__.py
  pos_sale_order_print/i18n/pos_sale_order_print.pot
  pos_sale_order_print/models/__init__.py
  pos_sale_order_print/models/pos_config.py
  pos_sale_order_print/models/pos_session.py
  pos_sale_order_print/models/res_config_settings.py
  pos_sale_order_print/readme/CONFIGURE.rst
  pos_sale_order_print/readme/CONTRIBUTORS.rst
  pos_sale_order_print/readme/DESCRIPTION.rst
  pos_sale_order_print/readme/USAGE.rst
  pos_sale_order_print/static/description/icon.png
  pos_sale_order_print/static/description/icon.svg
  pos_sale_order_print/static/description/index.html
  pos_sale_order_print/static/img/pos_config.png
  pos_sale_order_print/static/img/pos_print_popup.png
  pos_sale_order_print/static/img/pos_sale_order.png
  pos_sale_order_print/static/img/pos_standard_popup.png
  pos_sale_order_print/static/src/js/SaleOrderManagementScreen.esm.js
  pos_sale_order_print/static/src/js/pos_sale_order_print.esm.js
  pos_sale_order_print/views/res_config_settings_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/pos_sale_order_print/odoo/addons/pos_sale_order_print
  setup/pos_sale_order_print/setup.py
Labels: 16.0

#424 Syncing from upstream OCA/pos (14.0)
  README.md
  pos_pricelist_show_discount/README.rst
  pos_pricelist_show_discount/__manifest__.py
  pos_pricelist_show_discount/static/description/index.html
  pos_pricelist_show_discount/static/src/js/models.js
Labels: 14.0

#425 Syncing from upstream OCA/pos (13.0)
  README.md
  pos_invoice_required/README.rst
  pos_invoice_required/__init__.py
  pos_invoice_required/__manifest__.py
  pos_invoice_required/i18n/pos_invoice_required.pot
  pos_invoice_required/models/__init__.py
  pos_invoice_required/models/pos_config.py
  pos_invoice_required/models/pos_order.py
  pos_invoice_required/readme/CONFIGURE.rst
  pos_invoice_required/readme/CONTRIBUTORS.rst
  pos_invoice_required/readme/DESCRIPTION.rst
  pos_invoice_required/static/description/icon.png
  pos_invoice_required/static/description/index.html
  pos_invoice_required/static/src/js/models.js
  pos_invoice_required/static/src/js/screens.js
  pos_invoice_required/static/src/xml/templates.xml
  pos_invoice_required/views/pos_config_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/pos_invoice_required/odoo/addons/pos_invoice_required
  setup/pos_invoice_required/setup.py
Labels: 13.0

#427 Syncing from upstream OCA/pos (13.0)
  pos_customer_required/i18n/ca.po
  pos_customer_required/i18n/es.po
  pos_customer_required/i18n/fr.po
  pos_customer_required/i18n/nl_NL.po
  pos_default_partner/i18n/es.po
  pos_empty_home/i18n/it.po
  pos_fix_search_limit/i18n/es.po
  pos_fix_search_limit/i18n/it.po
  pos_fixed_discount/i18n/es.po
  pos_fixed_discount/i18n/it.po
  pos_margin/i18n/es.po
  pos_margin/i18n/fr.po
  pos_margin/i18n/it.po
  pos_margin/i18n/nl_NL.po
  pos_margin/i18n/pt.po
  pos_order_mgmt/i18n/ca.po
  pos_order_mgmt/i18n/es.po
  pos_order_mgmt/i18n/fr.po
  pos_order_mgmt/i18n/it.po
  pos_order_mgmt/i18n/pt.po
  pos_order_remove_line/i18n/it.po
  pos_order_to_sale_order/i18n/es.po
  pos_order_to_sale_order/i18n/fr.po
  pos_order_to_sale_order/i18n/it.po
  pos_order_to_sale_order/i18n/pt_BR.po
  pos_partner_lang/i18n/it.po
  pos_product_sort/i18n/it.po
  pos_quick_logout/i18n/es.po
  pos_quick_logout/i18n/fr.po
  pos_quick_logout/i18n/hr_HR.po
  pos_quick_logout/i18n/it.po
  pos_quick_logout/i18n/nl_NL.po
  pos_report_session_summary/i18n/ca.po
  pos_report_session_summary/i18n/ca_ES.po
  pos_report_session_summary/i18n/de.po
  pos_report_session_summary/i18n/es.po
  pos_report_session_summary/i18n/pt.po
  pos_session_pay_invoice/i18n/es.po
  pos_session_pay_invoice/i18n/fr.po
  pos_timeout/i18n/ca.po
  pos_user_restriction/i18n/es.po
  pos_user_restriction/i18n/it.po
Labels: 13.0

#429 Syncing from upstream OCA/pos (15.0)
  pos_event_sale/i18n/es.po
  pos_hide_cost_price_and_margin/i18n/es.po
  pos_hide_cost_price_and_margin/i18n/it.po
  pos_payment_change/i18n/de.po
  pos_payment_change/i18n/es.po
  pos_payment_change/i18n/fr.po
  pos_payment_change/i18n/it.po
  pos_product_display_default_code/i18n/it.po
  pos_receipt_hide_price/i18n/it.po
  pos_report_session_summary/i18n/ca.po
  pos_report_session_summary/i18n/ca_ES.po
  pos_report_session_summary/i18n/de.po
  pos_report_session_summary/i18n/es.po
  pos_report_session_summary/i18n/pt.po
  pos_user_restriction/i18n/es.po
  pos_user_restriction/i18n/it.po
Labels: 15.0

#430 Syncing from upstream OCA/pos (16.0)
  pos_access_right/i18n/ar.po
  pos_access_right/i18n/ca.po
  pos_access_right/i18n/es.po
  pos_access_right/i18n/fr.po
  pos_access_right/i18n/it.po
  pos_access_right/i18n/ru.po
  pos_customer_comment/i18n/es.po
  pos_customer_comment/i18n/it.po
  pos_discount_all/i18n/it.po
  pos_escpos_status/i18n/it.po
  pos_loyalty_redeem_payment/i18n/it.po
  pos_membership/i18n/es.po
  pos_membership/i18n/it.po
  pos_order_remove_line/i18n/it.po
  pos_order_to_sale_order/i18n/it.po
  pos_partner_birthdate/i18n/es.po
  pos_partner_birthdate/i18n/it.po
  pos_partner_firstname/i18n/ca.po
  pos_partner_firstname/i18n/ca_ES.po
  pos_partner_firstname/i18n/es.po
  pos_partner_firstname/i18n/fr_CH.po
  pos_partner_firstname/i18n/it.po
  pos_payment_change/i18n/de.po
  pos_payment_change/i18n/es.po
  pos_payment_change/i18n/fr.po
  pos_payment_change/i18n/it.po
  pos_payment_terminal/i18n/es.po
  pos_payment_terminal/i18n/fr.po
  pos_payment_terminal/i18n/hr_HR.po
  pos_payment_terminal/i18n/it.po
  pos_payment_terminal/i18n/nl_NL.po
  pos_product_quick_info/i18n/es.po
  pos_product_quick_info/i18n/it.po
  pos_receipt_hide_price/i18n/es.po
  pos_stock_available_online/i18n/es.po
  pos_stock_available_online/i18n/it.po
Labels: 16.0

#431 Syncing from upstream OCA/pos (14.0)
  pos_edit_order_line/i18n/es.po
  pos_margin/i18n/es.po
  pos_order_mgmt/i18n/es.po
Labels: 14.0

#432 Syncing from upstream OCA/pos (16.0)
  README.md
  pos_access_right/i18n/es.po
  pos_partner_firstname/i18n/es.po
  pos_payment_change/i18n/es.po
  pos_payment_terminal/i18n/es.po
  pos_product_packaging_multi_barcode/README.rst
  pos_product_packaging_multi_barcode/__init__.py
  pos_product_packaging_multi_barcode/__manifest__.py
  pos_product_packaging_multi_barcode/i18n/pos_product_packaging_multi_barcode.pot
  pos_product_packaging_multi_barcode/models/__init__.py
  pos_product_packaging_multi_barcode/models/pos_session.py
  pos_product_packaging_multi_barcode/models/product_packaging.py
  pos_product_packaging_multi_barcode/readme/CONTRIBUTORS.rst
  pos_product_packaging_multi_barcode/readme/CREDITS.rst
  pos_product_packaging_multi_barcode/readme/DESCRIPTION.rst
  pos_product_packaging_multi_barcode/readme/USAGE.rst
  pos_product_packaging_multi_barcode/static/description/icon.png
  pos_product_packaging_multi_barcode/static/description/index.html
  pos_product_packaging_multi_barcode/static/src/js/db.js
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/pos_product_packaging_multi_barcode/odoo/addons/pos_product_packaging_multi_barcode
  setup/pos_product_packaging_multi_barcode/setup.py
Labels: 16.0

#433 Syncing from upstream OCA/pos (8.0)
  pos_payment_entries_globalization/i18n/it.po
Labels: 8.0

#434 Syncing from upstream OCA/pos (12.0)
  pos_margin_accounting_role/i18n/it.po
  pos_remove_pos_category/i18n/it.po
  pos_ticket_extra_company_info/i18n/it.po
  pos_ticket_extra_company_info_l10n_fr/i18n/it.po
  pos_timeout/i18n/it.po
Labels: 12.0

#435 Syncing from upstream OCA/pos (13.0)
  pos_invoice_required/i18n/it.po
  pos_margin/i18n/it.po
  pos_quick_logout/i18n/it.po
  pos_user_restriction/i18n/it.po
Labels: 13.0

#436 Syncing from upstream OCA/pos (14.0)
  pos_backend_communication/i18n/it.po
  pos_customer_display/i18n/it.po
  pos_margin/i18n/it.po
  pos_order_to_sale_order/i18n/it.po
  pos_pricelist_show_discount/README.rst
  pos_pricelist_show_discount/__manifest__.py
  pos_pricelist_show_discount/demo/pos_config_demo.xml
  pos_pricelist_show_discount/demo/product_pricelist_demo.xml
  pos_pricelist_show_discount/i18n/it.po
  pos_pricelist_show_discount/i18n/pos_pricelist_show_discount.pot
  pos_pricelist_show_discount/static/description/index.html
  pos_pricelist_show_discount/tests/common.py
  pos_pricelist_show_discount/tests/test_pos_config_discount_pricelist.py
  pos_pricelist_show_discount/tests/test_pos_pricelist_show_discount.py
  pos_timeout/i18n/it.po
  pos_user_restriction/i18n/it.po
Labels: 14.0

#437 Syncing from upstream OCA/pos (15.0)
  pos_event_sale_session/i18n/it.po
  pos_user_restriction/i18n/it.po
Labels: 15.0

#438 Syncing from upstream OCA/pos (16.0)
  pos_access_right/i18n/it.po
  pos_minimize_menu/i18n/it.po
  pos_order_to_sale_order/i18n/it.po
  pos_partner_firstname/i18n/it.po
  pos_payment_terminal/i18n/it.po
  pos_product_packaging_multi_barcode/i18n/it.po
  pos_sale_order_print/i18n/it.po
Labels: 16.0

#439 Syncing from upstream OCA/pos (12.0)
  pos_meal_voucher/i18n/it.po
  pos_price_to_weight/i18n/it.po
  pos_tare/i18n/it.po
Labels: 12.0

#440 [t142462][FIX] setting correctly the IDs in the Domains
  pos_event_sale/models/pos_session.py
Labels: 16.0.project_sa_690

#442 Syncing from upstream OCA/pos (16.0)
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
Labels: 16.0

#443 Syncing from upstream OCA/pos (16.0)
  pos_sale_order_print/i18n/es.po
Labels: 16.0

#444 Syncing from upstream OCA/pos (12.0)
  pos_order_return_traceability/i18n/it.po
  pos_tare/i18n/it.po
Labels: 12.0

#445 Syncing from upstream OCA/pos (14.0)
  pos_margin/i18n/it.po
Labels: 14.0

#446 Syncing from upstream OCA/pos (14.0)
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  pos_empty_home/demo/pos_empty_home.xml
  pos_report_session_summary/views/report_session_summary.xml
  pos_reuse_pricelist/__init__.py
  pos_show_clock/views/pos_template.xml
Labels: 14.0

#447 Syncing from upstream OCA/pos (15.0)
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  pos_hide_cost_price_and_margin/__init__.py
  pos_report_session_summary/views/report_session_summary.xml
Labels: 15.0
