Repository brain-tec/pos, pull requests merged in 2023-12, with the labels that each got.

#474 Syncing from upstream OCA/pos (13.0)
  pos_invoice_required/i18n/it.po
Labels: 13.0

#476 Syncing from upstream OCA/pos (14.0)
  README.md
  pos_pricelist_show_discount/README.rst
  pos_pricelist_show_discount/__manifest__.py
  pos_pricelist_show_discount/static/description/index.html
  pos_pricelist_show_discount/static/src/js/models.js
Labels: 14.0

#477 Syncing from upstream OCA/pos (14.0)
  pos_order_return/i18n/it.po
Labels: 14.0

#479 Syncing from upstream OCA/pos (12.0)
  pos_report_order_payment/i18n/it.po
Labels: 12.0

#482 Integrate github.com/OCA/pos/pull/1021 into the TEST project branch
  pos_payment_method_image/README.rst
  pos_payment_method_image/__init__.py
  pos_payment_method_image/__manifest__.py
  pos_payment_method_image/i18n/fr.po
  pos_payment_method_image/models/__init__.py
  pos_payment_method_image/models/pos_payment_method.py
  pos_payment_method_image/models/pos_session.py
  pos_payment_method_image/readme/CONFIGURE.rst
  pos_payment_method_image/readme/CONTRIBUTORS.rst
  pos_payment_method_image/readme/DESCRIPTION.rst
  pos_payment_method_image/readme/ROADMAP.rst
  pos_payment_method_image/static/description/icon.png
  pos_payment_method_image/static/description/index.html
  pos_payment_method_image/static/description/pos_payment.png
  pos_payment_method_image/static/description/pos_payment_method_form.png
  pos_payment_method_image/static/src/css/pos_payment_method_image.css
  pos_payment_method_image/static/src/img/card-bank.png
  pos_payment_method_image/static/src/img/money.png
  pos_payment_method_image/static/src/img/pay-later.png
  pos_payment_method_image/static/src/js/PaymentScreen.js
  pos_payment_method_image/static/src/xml/pos_payment_method_image.xml
  pos_payment_method_image/views/view_pos_payment_method.xml
  setup/pos_payment_method_image/odoo/addons/pos_payment_method_image
  setup/pos_payment_method_image/setup.py
Labels: 16.0.project_sa_690.test.t144287

#487 Syncing from upstream OCA/pos (17.0)
  README.md
  pos_partner_birthdate/README.rst
  pos_partner_birthdate/__init__.py
  pos_partner_birthdate/__manifest__.py
  pos_partner_birthdate/i18n/es.po
  pos_partner_birthdate/i18n/it.po
  pos_partner_birthdate/i18n/pos_partner_birthdate.pot
  pos_partner_birthdate/models/__init__.py
  pos_partner_birthdate/models/pos_session.py
  pos_partner_birthdate/pyproject.toml
  pos_partner_birthdate/readme/CONTRIBUTORS.md
  pos_partner_birthdate/readme/DESCRIPTION.md
  pos_partner_birthdate/readme/newsfragments/.gitkeep
  pos_partner_birthdate/static/description/icon.png
  pos_partner_birthdate/static/description/index.html
  pos_partner_birthdate/static/src/js/ClientDetailsEdit.esm.js
  pos_partner_birthdate/static/src/xml/ClientDetailsEdit.xml
  setup/_metapackage/pyproject.toml
Labels: 17.0

#488 Syncing from upstream OCA/pos (16.0)
  README.md
  pos_order_to_sale_order_delivery/i18n/it.po
  pos_product_label/README.rst
  pos_product_label/__init__.py
  pos_product_label/__manifest__.py
  pos_product_label/i18n/it.po
  pos_product_label/i18n/pos_product_label.pot
  pos_product_label/models/__init__.py
  pos_product_label/models/pos_config.py
  pos_product_label/models/pos_session.py
  pos_product_label/models/res_config_settings.py
  pos_product_label/readme/CONTRIBUTORS.rst
  pos_product_label/readme/DESCRIPTION.rst
  pos_product_label/readme/USAGE.rst
  pos_product_label/static/description/icon.png
  pos_product_label/static/description/index.html
  pos_product_label/static/description/preview.png
  pos_product_label/static/src/PrintLabelButton.esm.js
  pos_product_label/static/src/PrintLabelButton.xml
  pos_product_label/static/src/PrintLabelPopup.esm.js
  pos_product_label/static/src/PrintLabelPopup.scss
  pos_product_label/static/src/PrintLabelPopup.xml
  pos_product_label/views/res_config_settings.xml
  pos_product_label/wizards/__init__.py
  pos_product_label/wizards/product_label_layout.py
  pos_reset_search/README.rst
  pos_reset_search/__init__.py
  pos_reset_search/__manifest__.py
  pos_reset_search/i18n/es.po
  pos_reset_search/i18n/it.po
  pos_reset_search/i18n/pos_reset_search.pot
  pos_reset_search/readme/CONTRIBUTORS.rst
  pos_reset_search/readme/DESCRIPTION.rst
  pos_reset_search/readme/USAGE.rst
  pos_reset_search/static/description/icon.png
  pos_reset_search/static/description/index.html
  pos_reset_search/static/src/js/Screens/ProductScreen/ProductScreen.js
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/pos_product_label/odoo/addons/pos_product_label
  setup/pos_product_label/setup.py
  setup/pos_reset_search/odoo/addons/pos_reset_search
  setup/pos_reset_search/setup.py
Labels: 16.0

#489 Syncing from upstream OCA/pos (12.0)
  pos_multiple_control/i18n/it.po
Labels: 12.0

#490 Syncing from upstream OCA/pos (12.0)
  pos_cash_control_multiple_config/i18n/it.po
  pos_cash_move_reason/i18n/it.po
  pos_multiple_control/i18n/it.po
Labels: 12.0

#491 Syncing from upstream OCA/pos (14.0)
  README.md
  pos_cash_move_reason/README.rst
  pos_cash_move_reason/__manifest__.py
  pos_cash_move_reason/static/description/index.html
  pos_cash_move_reason/tests/test_pos_cash_move_reason.py
  pos_margin/README.rst
  pos_margin/__manifest__.py
  pos_margin/static/description/index.html
  pos_margin/tests/test_module.py
  pos_payment_change/README.rst
  pos_payment_change/__manifest__.py
  pos_payment_change/static/description/index.html
  pos_payment_change/tests/test_module.py
Labels: 14.0

#492 Syncing from upstream OCA/pos (10.0)
  pos_customer_display/i18n/it.po
Labels: 10.0

#493 Syncing from upstream OCA/pos (16.0)
  README.md
  pos_financial_risk/README.rst
  pos_financial_risk/__init__.py
  pos_financial_risk/__manifest__.py
  pos_financial_risk/i18n/pos_financial_risk.pot
  pos_financial_risk/models/__init__.py
  pos_financial_risk/models/pos_config.py
  pos_financial_risk/models/pos_payment_method.py
  pos_financial_risk/models/pos_session.py
  pos_financial_risk/models/res_config_settings.py
  pos_financial_risk/readme/CONFIGURE.rst
  pos_financial_risk/readme/CONTRIBUTORS.rst
  pos_financial_risk/readme/DESCRIPTION.rst
  pos_financial_risk/readme/USAGE.rst
  pos_financial_risk/static/description/icon.png
  pos_financial_risk/static/description/index.html
  pos_financial_risk/static/src/js/PaymentScreen.esm.js
  pos_financial_risk/static/src/scss/pos.scss
  pos_financial_risk/static/src/xml/PaymentScreen.xml
  pos_financial_risk/views/pos_payment_method_views.xml
  pos_financial_risk/views/res_config_settings_views.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/pos_financial_risk/odoo/addons/pos_financial_risk
  setup/pos_financial_risk/setup.py
Labels: 16.0

#494 Syncing from upstream OCA/pos (14.0)
  README.md
  pos_disable_pricelist_selection/README.rst
  pos_disable_pricelist_selection/__manifest__.py
  pos_disable_pricelist_selection/i18n/it.po
  pos_disable_pricelist_selection/i18n/pos_disable_pricelist_selection.pot
  pos_disable_pricelist_selection/models/pos_config.py
  pos_disable_pricelist_selection/readme/CONTEXT.rst
  pos_disable_pricelist_selection/readme/DESCRIPTION.rst
  pos_disable_pricelist_selection/readme/USAGE.rst
  pos_disable_pricelist_selection/static/description/index.html
  pos_disable_pricelist_selection/static/src/js/PosModel.js
  pos_disable_pricelist_selection/static/src/js/SetPricelistButton.js
  pos_disable_pricelist_selection/views/assets.xml
  pos_disable_pricelist_selection/views/pos_config_view.xml
Labels: 14.0

#495 Syncing from upstream OCA/pos (16.0)
  README.md
  pos_financial_risk/i18n/it.po
  pos_order_to_sale_order_sale_financial_risk/README.rst
  pos_order_to_sale_order_sale_financial_risk/__init__.py
  pos_order_to_sale_order_sale_financial_risk/__manifest__.py
  pos_order_to_sale_order_sale_financial_risk/data/demo.xml
  pos_order_to_sale_order_sale_financial_risk/i18n/pos_order_to_sale_order_sale_financial_risk.pot
  pos_order_to_sale_order_sale_financial_risk/models/__init__.py
  pos_order_to_sale_order_sale_financial_risk/models/pos_session.py
  pos_order_to_sale_order_sale_financial_risk/models/sale_order.py
  pos_order_to_sale_order_sale_financial_risk/readme/DESCRIPTION.rst
  pos_order_to_sale_order_sale_financial_risk/static/description/icon.png
  pos_order_to_sale_order_sale_financial_risk/static/description/index.html
  pos_order_to_sale_order_sale_financial_risk/static/img/desktop_table.jpg
  pos_order_to_sale_order_sale_financial_risk/static/src/js/CreateOrderPopup.esm.js
  pos_order_to_sale_order_sale_financial_risk/static/src/js/models.esm.js
  pos_order_to_sale_order_sale_financial_risk/static/src/tests/tours/SaleFinancialRiskPosCompatibility.tour.esm.js
  pos_order_to_sale_order_sale_financial_risk/tests/__init__.py
  pos_order_to_sale_order_sale_financial_risk/tests/test_pos_ui.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/pos_order_to_sale_order_sale_financial_risk/odoo/addons/pos_order_to_sale_order_sale_financial_risk
  setup/pos_order_to_sale_order_sale_financial_risk/setup.py
Labels: 16.0

#496 Syncing from upstream OCA/pos (14.0)
  pos_disable_pricelist_selection/i18n/it.po
Labels: 14.0
