Repository brain-tec/pos, pull requests merged in 2023-07, with the labels that each got.

#362 Syncing from upstream OCA/pos (13.0)
  pos_payment_terminal/i18n/it.po
Labels: 13.0

#363 Syncing from upstream OCA/pos (14.0)
  pos_payment_method_cashdro/i18n/it.po
  pos_payment_terminal/i18n/it.po
Labels: 14.0

#364 Syncing from upstream OCA/pos (16.0)
  pos_loyalty_redeem_payment/i18n/it.po
  pos_payment_terminal/i18n/it.po
Labels: 16.0

#365 Syncing from upstream OCA/pos (14.0)
  README.md
  pos_session_pay_invoice/__manifest__.py
  pos_session_pay_invoice/wizard/cash_invoice_in.xml
  pos_session_pay_invoice/wizard/pos_box_cash_invoice_in.xml
  pos_session_pay_invoice/wizard/pos_box_cash_invoice_out.xml
Labels: 14.0

#366 Syncing from upstream OCA/pos (15.0)
  README.md
  pos_user_restriction/README.rst
  pos_user_restriction/__init__.py
  pos_user_restriction/__manifest__.py
  pos_user_restriction/i18n/es.po
  pos_user_restriction/i18n/it.po
  pos_user_restriction/i18n/pos_user_restriction.pot
  pos_user_restriction/models/__init__.py
  pos_user_restriction/models/pos_config.py
  pos_user_restriction/models/pos_session.py
  pos_user_restriction/models/res_users.py
  pos_user_restriction/readme/CONFIGURE.rst
  pos_user_restriction/readme/CONTRIBUTORS.rst
  pos_user_restriction/readme/DESCRIPTION.rst
  pos_user_restriction/readme/ROADMAP.rst
  pos_user_restriction/security/ir.model.access.csv
  pos_user_restriction/security/pos_security.xml
  pos_user_restriction/static/description/icon.png
  pos_user_restriction/static/description/index.html
  pos_user_restriction/tests/__init__.py
  pos_user_restriction/tests/test_pos_user_restriction.py
  pos_user_restriction/views/point_of_sale_views.xml
  pos_user_restriction/views/pos_config_views.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/pos_user_restriction/odoo/addons/pos_user_restriction
  setup/pos_user_restriction/setup.py
Labels: 15.0

#367 Update branch
  README.md
  pos_loyalty_redeem_payment/README.rst
  pos_loyalty_redeem_payment/__init__.py
  pos_loyalty_redeem_payment/__manifest__.py
  pos_loyalty_redeem_payment/i18n/es.po
  pos_loyalty_redeem_payment/i18n/it.po
  pos_loyalty_redeem_payment/i18n/pos_loyalty_redeem_payment.pot
  pos_loyalty_redeem_payment/models/__init__.py
  pos_loyalty_redeem_payment/models/loyalty_program.py
  pos_loyalty_redeem_payment/models/pos_config.py
  pos_loyalty_redeem_payment/models/pos_order.py
  pos_loyalty_redeem_payment/models/pos_payment.py
  pos_loyalty_redeem_payment/models/pos_payment_method.py
  pos_loyalty_redeem_payment/models/pos_session.py
  pos_loyalty_redeem_payment/readme/CONFIGURE.rst
  pos_loyalty_redeem_payment/readme/CONTRIBUTORS.rst
  pos_loyalty_redeem_payment/readme/DESCRIPTION.rst
  pos_loyalty_redeem_payment/readme/ROADMAP.rst
  pos_loyalty_redeem_payment/readme/USAGE.rst
  pos_loyalty_redeem_payment/static/description/icon.png
  pos_loyalty_redeem_payment/static/description/index.html
  pos_loyalty_redeem_payment/static/img/paymentMethod.png
  pos_loyalty_redeem_payment/static/img/paymentMethodCheck.png
  pos_loyalty_redeem_payment/static/img/redeemMethod.png
  pos_loyalty_redeem_payment/static/img/usage_1_code_popup.png
  pos_loyalty_redeem_payment/static/img/usage_2_amount_popup.png
  pos_loyalty_redeem_payment/static/img/usage_3_payment_line.png
  pos_loyalty_redeem_payment/static/src/js/PaymentScreen.esm.js
  pos_loyalty_redeem_payment/static/src/js/ResponsiveNumberPopup.esm.js
  pos_loyalty_redeem_payment/static/src/js/models.esm.js
  pos_loyalty_redeem_payment/static/src/scss/responsive_number_popup.scss
  pos_loyalty_redeem_payment/static/src/xml/Chrome.xml
  pos_loyalty_redeem_payment/static/src/xml/ResponsiveNumberPopup.xml
  pos_loyalty_redeem_payment/static/tests/tours/GiftCardRedeemPayment.tour.esm.js
  pos_loyalty_redeem_payment/static/tests/tours/helpers/ReceiptScreenTourMethods.js
  pos_loyalty_redeem_payment/tests/__init__.py
  pos_loyalty_redeem_payment/tests/test_frontend.py
  pos_loyalty_redeem_payment/views/loyalty_program_views.xml
  pos_loyalty_redeem_payment/views/pos_payment_method_views.xml
  pos_payment_terminal/i18n/it.po
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/pos_loyalty_redeem_payment/odoo/addons/pos_loyalty_redeem_payment
  setup/pos_loyalty_redeem_payment/setup.py
Labels: 16.0.project_sa_690

#370 Syncing from upstream OCA/pos (16.0)
  README.md
  pos_order_to_sale_order/__manifest__.py
  pos_order_to_sale_order/static/src/js/CreateOrderButton.js
Labels: 16.0

#371 Syncing from upstream OCA/pos (15.0)
  pos_cash_move_reason/i18n/es.po
  pos_event_sale/i18n/es.po
  pos_event_sale_registration_qr_code/i18n/es.po
  pos_event_sale_session/i18n/es.po
  pos_hide_cost_price_and_margin/i18n/es.po
  pos_lot_barcode/i18n/es.po
  pos_lot_selection/i18n/es.po
  pos_receipt_hide_price/i18n/es.po
  pos_sale_pos_event_sale_session/i18n/es.po
  pos_supplierinfo_search/i18n/es.po
Labels: 15.0

#372 Syncing from upstream OCA/pos (12.0)
  pos_place/i18n/it.po
Labels: 12.0

#373 Syncing from upstream OCA/pos (8.0)
  pos_remove_pos_category/i18n/it.po
Labels: 8.0

#374 Syncing from upstream OCA/pos (10.0)
  pos_remove_pos_category/i18n/it.po
Labels: 10.0

#376 Syncing from upstream OCA/pos (16.0)
  README.md
  pos_margin/README.rst
  pos_margin/__init__.py
  pos_margin/__manifest__.py
  pos_margin/i18n/es.po
  pos_margin/i18n/pos_margin.pot
  pos_margin/models/__init__.py
  pos_margin/models/pos_config.py
  pos_margin/models/res_config_settings.py
  pos_margin/readme/CONFIGURE.rst
  pos_margin/readme/CONTRIBUTORS.rst
  pos_margin/readme/DESCRIPTION.rst
  pos_margin/readme/HISTORY.rst
  pos_margin/readme/ROADMAP.rst
  pos_margin/readme/USAGE.rst
  pos_margin/report/__init__.py
  pos_margin/report/pos_order_report.py
  pos_margin/static/description/icon.png
  pos_margin/static/description/index.html
  pos_margin/static/description/pos_config_form.png
  pos_margin/static/description/pos_config_setting.png
  pos_margin/static/description/pos_front_end.png
  pos_margin/static/description/pos_order_form.png
  pos_margin/static/src/css/pos_margin.css
  pos_margin/static/src/js/OrderSummaryMargin.esm.js
  pos_margin/static/src/js/models.esm.js
  pos_margin/static/src/xml/pos_margin.xml
  pos_margin/views/res_config_settings_view.xml
  pos_margin/views/view_pos_order.xml
  pos_order_remove_line/__manifest__.py
  pos_order_remove_line/static/src/js/orderline.esm.js
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/pos_margin/odoo/addons/pos_margin
  setup/pos_margin/setup.py
Labels: 16.0

#377 Syncing from upstream OCA/pos (14.0)
  README.md
  pos_product_template/__manifest__.py
  pos_product_template/static/src/js/SelectVariantPopup.js
Labels: 14.0

#378 Syncing from upstream OCA/pos (15.0)
  pos_event_sale_registration_qr_code/i18n/it.po
  pos_payment_change/i18n/es.po
  pos_sale_pos_event_sale/i18n/es.po
Labels: 15.0

#379 Syncing from upstream OCA/pos (12.0)
  pos_partner_firstname/i18n/es.po
Labels: 12.0

#380 Syncing from upstream OCA/pos (13.0)
  pos_event_sale/i18n/it.po
Labels: 13.0

#381 Syncing from upstream OCA/pos (14.0)
  pos_partner_firstname/i18n/es.po
Labels: 14.0

#383 [IMP] pos_event_sale
  pos_event_sale/static/src/js/models/Order.js
  pos_event_sale/static/src/js/models/Orderline.js
  pos_event_sale/static/src/js/models/PosGlobalState.js
  pos_event_sale/static/src/xml/ReceiptScreen/EventRegistrationReceipt.xml
Labels: 16.0.project_sa_690

#384 Syncing from upstream OCA/pos (14.0)
  pos_product_template/i18n/es.po
Labels: 14.0

#385 [IMP] Prevent race condition on payment validation
  pos_event_sale/static/src/js/models/PosGlobalState.js
Labels: 16.0.project_sa_690
