Repository brain-tec/pos, pull requests merged in 2023-08, with the labels that each got.

#386 Syncing from upstream OCA/pos (14.0)
  pos_margin/i18n/it.po
Labels: 14.0

#387 Syncing from upstream OCA/pos (16.0)
  pos_margin/i18n/it.po
Labels: 16.0

#388 Syncing from upstream OCA/pos (12.0)
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  hw_telium_payment_terminal/test-scripts/telium-test.py
Labels: 12.0

#389 Syncing from upstream OCA/pos (12.0)
  README.md
  pos_product_mergeable_line/README.rst
  pos_product_mergeable_line/__init__.py
  pos_product_mergeable_line/__manifest__.py
  pos_product_mergeable_line/i18n/fr.po
  pos_product_mergeable_line/i18n/pos_product_mergeable_line.pot
  pos_product_mergeable_line/models/__init__.py
  pos_product_mergeable_line/models/product_template.py
  pos_product_mergeable_line/readme/CONTRIBUTORS.rst
  pos_product_mergeable_line/readme/DESCRIPTION.rst
  pos_product_mergeable_line/static/description/icon.png
  pos_product_mergeable_line/static/description/index.html
  pos_product_mergeable_line/static/src/js/models.js
  pos_product_mergeable_line/views/templates.xml
  pos_product_mergeable_line/views/view_product_template.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/pos_product_mergeable_line/odoo/addons/pos_product_mergeable_line
  setup/pos_product_mergeable_line/setup.py
Labels: 12.0

#390 Syncing from upstream OCA/pos (16.0)
  README.md
  pos_order_to_sale_order/__manifest__.py
  pos_order_to_sale_order/static/src/js/CreateOrderPopup.js
Labels: 16.0

#391 Syncing from upstream OCA/pos (14.0)
  pos_session_pay_invoice/i18n/es.po
Labels: 14.0

#392 Syncing from upstream OCA/pos (16.0)
  README.md
  pos_order_to_sale_order/__manifest__.py
  pos_order_to_sale_order/models/sale_order.py
  pos_order_to_sale_order/models/sale_order_line.py
Labels: 16.0

#393 Syncing from upstream OCA/pos (12.0)
  README.md
  pos_tare/__manifest__.py
  pos_tare/static/src/js/screens.js
Labels: 12.0

#394 Syncing from upstream OCA/pos (16.0)
  README.md
  pos_order_to_sale_order_report/README.rst
  pos_order_to_sale_order_report/__init__.py
  pos_order_to_sale_order_report/__manifest__.py
  pos_order_to_sale_order_report/i18n/pos_order_to_sale_order_report.pot
  pos_order_to_sale_order_report/models/__init__.py
  pos_order_to_sale_order_report/models/pos_config.py
  pos_order_to_sale_order_report/models/res_config_settings.py
  pos_order_to_sale_order_report/readme/CONFIGURE.rst
  pos_order_to_sale_order_report/readme/CONTRIBUTORS.rst
  pos_order_to_sale_order_report/readme/DESCRIPTION.rst
  pos_order_to_sale_order_report/readme/USAGE.rst
  pos_order_to_sale_order_report/static/description/icon.png
  pos_order_to_sale_order_report/static/description/index.html
  pos_order_to_sale_order_report/static/img/pos_config.png
  pos_order_to_sale_order_report/static/src/js/Popups/CreateOrderPopup.esm.js
  pos_order_to_sale_order_report/views/res_config_settings_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/pos_order_to_sale_order_report/odoo/addons/pos_order_to_sale_order_report
  setup/pos_order_to_sale_order_report/setup.py
Labels: 16.0

#395 Syncing from upstream OCA/pos (16.0)
  README.md
  pos_customer_comment/README.rst
  pos_customer_comment/__manifest__.py
  pos_customer_comment/readme/CONTRIBUTORS.rst
  pos_customer_comment/static/description/index.html
  pos_customer_comment/static/src/js/PartnerDetailsEdit.esm.js
  pos_customer_comment/static/src/xml/PartnerDetailsEdit.xml
  pos_partner_birthdate/README.rst
  pos_partner_birthdate/__manifest__.py
  pos_partner_birthdate/readme/CONTRIBUTORS.rst
  pos_partner_birthdate/static/description/index.html
  pos_partner_birthdate/static/src/js/ClientDetailsEdit.esm.js
  pos_partner_birthdate/static/src/xml/ClientDetailsEdit.xml
Labels: 16.0

#396 [IMP] Prevent sending confirmation mails to contact without email
  pos_event_sale/models/__init__.py
  pos_event_sale/models/event_mail.py
  pos_event_sale/models/pos_session.py
  pos_event_sale/static/src/js/models/PosGlobalState.js
  pos_event_sale/static/src/scss/pos_event_sale.scss
Labels: 16.0.project_sa_690.pos_event_sale

#397 [IMP] Prevent long delays on validating a paid order
  pos_event_sale/models/__init__.py
  pos_event_sale/models/event_mail.py
  pos_event_sale/models/pos_session.py
  pos_event_sale/static/src/js/models/PosGlobalState.js
  pos_event_sale/static/src/scss/pos_event_sale.scss
Labels: 16.0.project_sa_690
